# Generated by Django 4.1.7 on 2023-06-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalsectionmodel',
            name='background',
            field=models.TextField(default='', max_length=255),
        ),
    ]
